# Generated by Django 2.1.4 on 2018-12-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
