# Generated by Django 2.2.10 on 2021-04-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0002_auto_20200816_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_expires',
        ),
    ]
