# Generated by Django 2.1.4 on 2019-04-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0002_auto_20190428_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='devices', to='controller.Device'),
        ),
    ]
