# Generated by Django 2.1.4 on 2019-04-28 22:50

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('playmaker', '0003_auto_20190428_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Permission')),
                ('scope', models.CharField(max_length=256)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='playmaker.Controller')),
                ('listener', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='playmaker.Listener')),
            ],
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
