# Generated by Django 2.2 on 2019-04-30 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0003_auto_20190428_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=256)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='playmaker.Controller')),
                ('listener', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='playmaker.Listener')),
            ],
        ),
    ]
