# Generated by Django 2.2 on 2019-08-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0004_auto_20190729_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sp_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sp_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
