# Generated by Django 2.2 on 2019-10-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0007_auto_20190820_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_controller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_listener',
            field=models.BooleanField(default=False),
        ),
    ]
