# Generated by Django 2.2.7 on 2020-03-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0008_auto_20191026_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shouldPoll',
            field=models.BooleanField(default=False),
        ),
    ]
