# Generated by Django 2.2.7 on 2020-03-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0010_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hasActivePoller',
            field=models.BooleanField(default=False),
        ),
    ]
