# Generated by Django 2.2.7 on 2020-03-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0011_user_hasactivepoller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pollingThread',
            field=models.CharField(null=True, max_length=128),
        ),
    ]
