# Generated by Django 2.2.7 on 2020-03-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0014_listener_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='rooms.Room'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
