# Generated by Django 2.2.7 on 2020-03-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0015_auto_20200327_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spmodel',
            name='sp_id',
            field=models.CharField(max_length=255),
        ),
    ]
