# Generated by Django 2.2.7 on 2020-03-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0016_auto_20200327_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listeners', to='rooms.Room'),
        ),
    ]
