# Generated by Django 2.2.7 on 2020-03-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0017_auto_20200330_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_action',
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(null=True),
        ),
    ]
