# Generated by Django 2.2 on 2019-08-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20190817_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
