# Generated by Django 2.2 on 2019-08-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20190823_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='uri',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
