# Generated by Django 2.2 on 2019-09-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_album_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration_ms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='popularity',
            field=models.IntegerField(null=True),
        ),
    ]
