# Generated by Django 2.2.7 on 2019-11-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20190902_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='album', to='songs.Image'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='artist', to='songs.Image'),
        ),
    ]
