# Generated by Django 2.2.7 on 2020-03-19 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20191110_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='songs_rel', to='songs.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='on_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs_rel', to='songs.Album'),
        ),
    ]
