# Generated by Django 2.2.7 on 2020-03-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_auto_20200319_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='on_album',
            new_name='albums',
        ),
    ]
