# build environment
FROM node:12.2.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install -g
RUN npm install -g react-scripts@3.0.1
RUN npm install -g --unsafe-perm node-sass@4.14.1
RUN npm update
COPY . /app
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
RUN apk update && apk add vim
RUN apk add netcat-openbsd bc curl wget git bash
RUN apk add libressl
ENV D=/usr/share/nginx/html
#Inject this in the future as a build arg.

ADD nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
