version: '2'
services:
  interface:
    env_file:
      - production.env
    volumes:
      - './playmaker:/app:rw'
      - $HOME/docker/volumes/static:/var/www/static
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
      args:
        - TAG=${TAG}
    volumes:
      - /root/certs/playmaker.social:/etc/nginx/ssl/letsencrypt/playmaker.social/:rw
      - $HOME/docker/volumes/static:/var/www/static
    ports:
          - "80:80"
          - "443:443"
    depends_on:
      - interface
    env_file:
      - production.env
    restart: always
