version: '2'
services:
  interface:
    environment:
      - MY_HOST=https://test.myplaymkr.co
    env_file:
      - production.env
  frontend:
    build:
      context: ./playmaker/playmkr-ui
    depends_on:
      - interface
    restart: always
  nginx:
    build:
      context: ./nginx
      args:
        - TAG=${TAG}
    volumes:
      - /root/certs/myplaymkr.co:/etc/nginx/ssl/myplaymkr.co:rw
    ports:
      - "80:80"
      - "443:443"
