version: '2'
services:
  interface:
    env_file:
      - dev.env
    volumes:
      - './playmaker:/app:rw'
      - '/var/www/static:/var/www/static'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE=http://localhost:5000/api
