version: '2'
services:
  interface:
    environment:
      - MY_HOST=https://test.myplaymkr.co
    env_file:
      - production.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
      args:
        - TAG=${TAG}
    volumes:
      - /root/certs/test.myplaymkr.co:/etc/nginx/ssl/letsencrypt/test.myplaymkr.co/:rw
    ports:
          - "80:80"
          - "443:443"
    depends_on:
      - interface
    environment:
      - REACT_APP_API_BASE=https://test.myplaymkr.co
    restart: always
#  nginx:
#    container_name: nginx
#    build:
#      context: ./nginx
#      args:
#        - TAG=${TAG}
#    volumes:
#      - /root/certs/myplaymkr.co:/etc/nginx/ssl/myplaymkr.co:rw
#    ports:
#      - "80:80"
#      - "443:443"
