version: '2'
services:
  interface:
    container_name: interface
    build:
      context: ./playmaker
    image: playmaker-interface
    volumes:
      - ./playmaker:/app:rw
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_PASSWORD=test
    env_file:
      - production.env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    build:
      context: ./postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
