version: '2'
services:
  interface:
    container_name: interface
    build:
      context: ./playmaker
    image: playmaker-interface:${TAG}
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_PASSWORD=test
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    build:
      context: ./postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      args:
        - TAG=${TAG}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - interface
    restart: always