#!/bin/sh

# Make sure only root can run our script

#. /etc/dns/config

gcloud compute instances start playmaker-api-1

rm -rf transaction.yaml

#Gather IP
IP_ADDRESS=$(gcloud compute instances describe playmaker-api-1 --zone us-central1-a | grep natIP | awk {'print $2'})

#Gather hostname
IO_HOSTNAME=$(gcloud compute instances describe playmaker-api-1 --zone us-central1-a | grep url: | awk {'print $2'})

OLD_IP_ADDRESS=$(gcloud dns record-sets list --zone=playmaker-social --name=$IO_HOSTNAME.playmaker.social --format=json | jq -r .[0].rrdatas[0])

gcloud dns record-sets transaction start -z=playmaker-social
gcloud dns record-sets transaction remove --zone playmaker-social --name $IO_HOSTNAME.playmaker.social. --ttl 120 --type A $OLD_IP_ADDRESS
gcloud dns record-sets transaction add --zone playmaker-social --name $IO_HOSTNAME.playmaker.social. --ttl 120 --type A $IP_ADDRESS
gcloud dns record-sets transaction execute -z=playmaker-social
