# Generated by Django 2.2 on 2019-07-26 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playmaker', '0003_auto_20190716_0103'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_controller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('spmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playmaker.SPModel')),
                ('is_active', models.BooleanField()),
                ('is_private_session', models.BooleanField()),
                ('is_restricted', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=64)),
                ('volume_percent', models.IntegerField()),
            ],
            bases=('playmaker.spmodel',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Controller')),
            ],
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.ManyToManyField(blank=True, related_name='listeners_device', to='controller.Device')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Group')),
                ('me', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_listener', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=256)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Controller')),
                ('listener', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Listener')),
            ],
        ),
    ]
