# Generated by Django 2.1.4 on 2019-04-27 23:47

from django.db import migrations, models
from django.conf import settings
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('is_private_session', models.BooleanField()),
                ('is_restricted', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=64)),
                ('volume_percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me',
                 models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_controller',
                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller',
                 models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group',
                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.ManyToManyField(related_name='devices', to='controller.Device')),
                ('me', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_listener',
                                            to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
