# Generated by Django 2.2 on 2019-07-29 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='me',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs', models.ManyToManyField(to='songs.Song')),
            ],
        ),
        migrations.AddField(
            model_name='controller',
            name='queue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Queue'),
        ),
    ]
