# Generated by Django 2.2 on 2019-07-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playmaker', '0003_auto_20190716_0103'),
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AddField(
            model_name='device',
            name='spmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playmaker.SPModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='listeners',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='controller.Listener'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listener',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='listeners_device', to='controller.Device'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=256)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Controller')),
                ('listener', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='controller.Listener')),
            ],
        ),
    ]
