# Generated by Django 2.2 on 2019-08-27 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_album_uri'),
        ('controller', '0002_auto_20190823_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='current_song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_groups', to='songs.Song'),
        ),
    ]
