# Generated by Django 2.2 on 2019-08-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_queue_current_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uri',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
