# Generated by Django 2.2 on 2019-09-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_device_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='next_pos',
            field=models.IntegerField(default=0),
        ),
    ]
