# Generated by Django 2.2 on 2019-09-03 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_queue_next_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='queue',
        ),
        migrations.AddField(
            model_name='queue',
            name='controller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controller.Controller'),
        ),
    ]
