# Generated by Django 2.2 on 2019-09-03 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_auto_20190903_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinqueue',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_q', to='songs.Song'),
        ),
    ]
