# Generated by Django 2.2 on 2019-09-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_auto_20190903_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_selected',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
