# Generated by Django 2.2.7 on 2019-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_device_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uri',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
