# Generated by Django 2.2.7 on 2019-11-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0010_auto_20191114_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='current_song',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
