# Generated by Django 2.2.7 on 2020-03-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0015_auto_20200322_0347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
