# Generated by Django 2.2.7 on 2020-03-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0016_delete_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listener',
            name='group',
        ),
        migrations.RemoveField(
            model_name='listener',
            name='me',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='listener',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Listener',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
