# Generated by Django 2.2.7 on 2020-05-16 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0017_auto_20200327_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songinqueue',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='songinqueue',
            name='song',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
        migrations.DeleteModel(
            name='SongInQueue',
        ),
    ]
