# Generated by Django 2.2.7 on 2020-05-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200516_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='controller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='controller.Controller'),
        ),
    ]
