# Generated by Django 2.2.7 on 2019-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.DateTimeField()),
                ('user', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('Bug/Problem', 'Bug/Problem'), ('Feature Request', 'Feature Request')], max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
