# Generated by Django 2.2.7 on 2020-03-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
